### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by colinhacks** [davidmdm/myzod#1]
Hey David,

This is really impressive stuff! Your code is much prettier than mine 😅 Any interest in merging this into Zod and coming on as a maintainer? If we can bring your lib up to feature parity with Zod (from a quick scan it looks like you're missing recursive schemas, `.nonempty` arrays, and `.nonstrict` objects), I'd be happy to merge this in as zod@1.3. I really like all the improvements you've made.

Regardless shoot me an email (address is on my profile), I'd love to find a time to chat. The reason I was dragging my feet on pick, omit, partial, etc is because the obvious implementations didn't work well for recursive schemas. I'm currently working on a big rewrite that will make it easier to deal with recursion, I'd be interested in running some of those ideas by you. 👍

Colin

**Comment by colinhacks** [comment]
Oops, looks like you do support an equivalent to `.nonstrict` - my bad. 

As I read through your code more thoroughly, I'm really loving all the improvements you've made - pick, omit, partial, deep partial, creating enum schemas from actual enums, extra string/number validators, unknowns, allowing ISO strings as dates, number coercion...good stuff!

**Comment by davidmdm** [comment]
Yeah .nonStrict is the same as the allowUnknown option in myzod. Also nonEmpty for arrays is the same as setting the min to 1 in myzod.

I think it is not possible to support recursive schemas in myzod, unfortunately.

**Comment by davidmdm** [comment]
@vriad I am interested in discussing your ideas. I wrote you an email!

**Comment by rockymeza** [comment]
Hi, just a passerby, but did y'all decide if you will merge?

**Comment by boy51** [comment]
I too am interested in knowing.
