### ISSUE TITLE
V1.0.0 release

### ISSUE THREAD

**Issue by davidmdm** [davidmdm/myzod#13]
@pierreis ,

I have taken a little more than a week off from actively developing myzod and am now recharged. I've been wondering if it would be a good idea to release version 1.0.0

The only feature I haven't done that people have asked for was to have every error fields on ValidationErrors. ie:

```typescript
const personSchema = mz.object({ name: mz.string(), lastname: mz.string() });
const err = personSchema.try({ name: null });

// Possibly fields would contain the failed keys and their error message
err.fields = {
  name: 'expected type string but got null',
  lastname: 'expected type string but got undefined',
}
```

Instead of simply throwing on the first error encountered. This would make it useful for Form Validations on the front-end. Custom default error messages would need to go hand in hand with this.

So my question is, should this feature be implemented and if yes before v1.0.0? 

My feeling is that releasing a non-alpha version might help with adoption and provide more feedback and feature requests. 

Just looking for thoughts, and you're my number one collaborator. Thanks for your efforts and being active within myzod.

**Comment by pierreis** [comment]
Hi David,

Sure. I think it is okay to release.

Returning an error array is an important feature (that actually would help me a lot), but I feel like there is no strong rationale here to do it before 1.0 rather than in a future version 1.1.

P.

**Comment by boy51** [comment]
Hi, whats the progress on error fields? I'm using myzod in a project and feeling great about it, but now I need it to do forms for me and it doesn't do enough yet. I could help contributing if it helps.

I wrote this before I realized you guys are already planning this feature

> my suggestion is to have an error object similar to what [formik expects in its validate function](https://formik.org/docs/guides/validation), which is essentially a `Record<keyof T, string>` where the values are the error message. This would make validation with Formik incredibly easy:
> 
> ```ts
> const validate = ( vals: T ) => {
>    const res = myzodSchema.try(vals)
>    if (res instanceof ValidationError) return res.errors
> }
> 
> ```
> 
> Other than that, it seems like currently parsing will stop at the first wrong value. For forms it would be reasonable to have an option to pass in that will parse the entire object, like `abortEarly` in yup, as well as having the ability to provide messages in the schema.
> 
> Also, myzod makes error.message s like this: `error at [0].id - expected number to be greater than or equal to 99999 but got 1`
> 
> It seems like I could use the second part of the message to output as an error, but its annoying that I would have to regex the first part.
> 
> I'd be interested to hear your plans/opinions about this and maybe I can make a PR if I find some time.
