### ISSUE TITLE
Add create method as a compile time safe variant of parse

### ISSUE THREAD

**Issue by kasperpeulen** [davidmdm/myzod#17]
Let me first say I absolutely love this library! I have here a feature request that may seem a bit odd, but let's explain where I come from.

So say I have this schema:

```ts
export const Page = object({
  id: string().default(() => ulid()),
  url: string(),
  readAt: array(date()).default([]),
  createdAt: date().default(() => new Date()),
  updatedAt: date().default(() => new Date()),
})

export type Page = Infer<typeof Page>;
```

So I can use `Page.parse(userInput)` to validate forms, where a user may want to add a page it wants to read. That is great. 

I also can use `Page.parse(backendData)` that to check if the data I get from an external source, actually has the shape, I expect it to have. And otherwise fail early, exactly where I made this asssumption.

I can use the `Page` type to pass around this types in my functions, but also to generate objects myself, for example in a unit test.

```ts
const pageMock: Page = {
  id: ulid(),
  url: 'https://github.com/davidmdm/myzod',
  readAt: [],
  createdAt: new Date(),
  updatedAt: new Date(),
};
```

You could write a factory function for this, so that you only have to write:
`createPage({ url: 'https://github.com/davidmdm/myzod' });`

For example, like this:
```ts
export function defaultPage() {
  return {
    id: ulid(),
    readAt: [] as Date[],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
}

export type OptionalKeys<T extends object, K extends keyof T> = Partial<Pick<T, K>> & Omit<T, K>;

export function createPage(page: OptionalKeys<Page, keyof ReturnType<typeof defaultPage>>): Page {
  return {
    ...defaultPage(),
    ...page,
  };
}
```

In some sense, Page.parse is also a great factory function, I can also just do:

```ts
const newPage = Page.parse({ url: 'https://github.com/davidmdm/myzod' });
```

However, there is now not any autocompletion or compile time checks, I would have if I write the factory function myself.

So therefore the question, could myzod have a Page.create kind of function, that does something similar as `Page.parse` except that it knows exactly what it needs, so that it fails on compile time, and safe and sound on runtime. In this case, that would mean that it accepts:

```ts
interface PageInput {
  id?: string
  url: string,
  readAt?: Date[]
  createdAt?: Date
  updatedAt?: Date
}
```

As all fields except `url` have a default value.

**Comment by davidmdm** [comment]
Hey thanks for your feedback!!!

This has been explored once before. The issue with how this works is that current when a schema calls default it returns a new instance of the same schema but with an internally stored default value/function. That makes it hard to be able to tell at compile time that defaulted values are optional. 

I had tried by implementing Default as a wrapper type similar to NullType/OptionalType but I had run into trouble with the tsc compiler for reasons that are somewhat unclear to me. I am not saying this couldn't be done but it would be quite a bit more high effort than might be imagined.

I will leave this open for now as I think this does deserve a second look into, but I don't see it being an easy quick change unfortunately :( 

In the meantime, the dirtiest helper you can write yourself, but is far from ideal would be to write something like this:

```typescript
const createPage = (input: Partial<Page> & Pick<Page, 'url'>) => pageSchema.parse(input);  
```
Where Unfortunately you are manually making all fields optional and Picking the ones you want to enforce as required.
Subideal for sure but maybe slightly better than rewriting a full createPage factory by hand.

I'll try and investigate if I can infer the defaultable values as soon as I can.

Thanks for using myzod!
