### ISSUE TITLE
License

### ISSUE THREAD

**Issue by smichel17** [davidmdm/myzod#25]
Hi, this looks like a great project! Since it's on npm, it _seems_ like you intend for others to use it / for it to be open source, but there's currently no license; it would be great if you can clarify that :slightly_smiling_face:

**Comment by davidmdm** [comment]
You are correct. I just overlooked it. It's obviously for people to use as they will. I am no specialist in lisences. Would MIT suffice?

**Comment by pierreis** [comment]
Assuming you want to keep it simple, MIT looks good to me 👍

**Comment by smichel17** [comment]
I like MIT for a permissive license — available to the greatest number of developers and the easiest to include in a project — and AGPL v3 or later for a copyleft license — providing the strongest safeguards on freedom *for end users*, at the expense of some restrictions/hassle for developers.

**Comment by davidmdm** [comment]
added MIT licsense to the repo, and package.json. Thanks guys.
