### ISSUE TITLE
validateAt - validate a specific field

### ISSUE THREAD

**Issue by TriStarGod** [davidmdm/myzod#26]
Hi, does this library offer a way to validate a specific field like yup's [validateAt](https://github.com/jquense/yup#mixedvalidateatpath-string-value-any-options-object-promiseany-validationerror)? How about exit validation on first error?

Thanks for any help you can provide. Great library!

**Comment by davidmdm** [comment]
Hi, I just looked at yup's validateAt, and no `myzod` does not provide anything that specific. As for exit validation on first error, unless I misunderstand you, that is generally myzod's approach to errors. It doesn't collect all possible errors in a shape but returns the first one immediately.

**Comment by TriStarGod** [comment]
Ah. I thought it returned all errors. Thanks for the fast response!
