### ISSUE TITLE
typing function arg as instance of myzod

### ISSUE THREAD

**Issue by vorticalbox** [davidmdm/myzod#28]
basic idea is that I have a function that I pass an object and a schema to  and then parse it;

```
export function testObject(input: any, schema: someThing){
    return schema.parse(input);
}
```

question is how I type the schema so that it accepts a instance of myzod?

**Comment by davidmdm** [comment]
Great question! Here is how you would do it:

```typescript
import {Type, Infer} from 'myzod';

function parseWrapper<T extends Type<any>>(input: any, schema: T): Infer<T>  {
    return schema.parse(input);
}
```

Hope that helps!
