### ISSUE TITLE
TypeError Message support

### ISSUE THREAD

**Issue by davidmdm** [davidmdm/myzod#31]
A need to add support for user defined messages for schema type errors

**Comment by boy51** [comment]
Works as expected, only thing I would kinda expect is to be able to pass this to TypeOptions, i.e. `z.string({ typeError: "..." })` since min or max works similarly, but thats just me

**Comment by davidmdm** [comment]
And do you think having simple function support is enough for working with locales

**Comment by boy51** [comment]
Sure, its enough for anyone to implement it themselves.
