### ISSUE TITLE
Regression: cannot set both optional() and nullable() on schema

### ISSUE THREAD

**Issue by ruslang02** [davidmdm/myzod#40]
Both versions 1.7.0 and 1.7.1 have a regression regarding not being able to set both optional and nullable properties. Consequently, TypeScript cannot determine the type properly as well.

Here is a quick test:
![image](https://user-images.githubusercontent.com/25264730/118270774-26f5c800-b4c9-11eb-8593-037994026642.png)

On 1.6.1 this issue is not present.

**Comment by davidmdm** [comment]
HI Ruslang, I don't understand exactly what the problem is.
a.schema and b.schema seem to be exactly what I would expect them to be.
Also my intilisense seems to be working, and I added a test case for optional().nullable() schemas and it seems to work as expected.

Can you either provide more info, or some kind of example where it doesn't work?

**Comment by davidmdm** [comment]
ok, I see that chaining optional() off of nullable doesn't seem to work in the type-system. will investigate

**Comment by ruslang02** [comment]
Let's say I have a schema that looks like this
```typescript
const PeriodSchema = object({
    month: number().nullable().optional(),
    day: number().nullable().optional(),
}).allowUnknownKeys();
```

I expect the resulting type/schema to look like this:
```typescript
type Period = {
    month?: number | null | undefined;
    day?: number | null | undefined;
}
```

However with the latest version the behaviour has changed, and I get this type instead:
```typescript
type Period = {
    month: number | null;
    day: number | null;
}
```
or this one, depending on the order:
```typescript
type Period = {
    month: number | undefined;
    day: number | undefined;
}
```

**Comment by davidmdm** [comment]
I have deployed v1.7.2. Please let me know if this fixes your issue. I have added these tests to myzod to hopefully make sure this never happens again;

```ts
 it('optional/nullable primitive', () => {
    const schema = z.string().optional().nullable();
    const x: AssertEqual<z.Infer<typeof schema>, string | null | undefined> = true;
    x;
  });

  it('nullable/optional primitive', () => {
    const schema = z.string().nullable().optional();
    const x: AssertEqual<z.Infer<typeof schema>, string | null | undefined> = true;
    x;
  });
```

**Comment by ruslang02** [comment]
It fixes the issue, thanks!
