### ISSUE TITLE
int() support on number?

### ISSUE THREAD

**Issue by delaneyj** [davidmdm/myzod#45]
Could be added as `z.number({integer:true})`?

**Comment by davidmdm** [comment]
Hi @delaneyj,

Myzod has the withPredicate functionality for this reason!

```ts
const integerSchema = mz
  .number()
  .withPredicate(Number.isInteger, value => `number must be an integer but got: ${value}`)
```

This will create a number schema that must be an integer with the given error string on error.
Indeed you can create any type of validation, isOdd, isEven, isPositive, isGreater than, using predicates.
And afterwards that schema can be used in other schemas:

```ts
const personSchema = mz.object({
  name: mz.string(),
  age: integerSchema,
})
```

Does that work for you?

**Comment by delaneyj** [comment]
Yep, makes sense.  Thanks for the clarification.
