### ISSUE TITLE
Expose types that make up public boundary with module

### ISSUE THREAD

**Issue by DavidRigglemanININ** [davidmdm/myzod#46]
So far I'm really liking this library, so keep up the good work! One issue I've ran into is being forced into disabling some typescript-eslint rules because of the lack of publicly exposed types. Specifically, I'm forced to disable explicit-module-boundary-types and no-implicity-any because I'm wanting to create some wrappers with enhanced functionality (like support for forcing numbers to be integer or a certain granularity). And so I've abstracted out the code well enough so that I could swap out for a different validation in the library if I needed to (hoping not to do that!). But the lack of types means I have to leave off types on my functions or make my function parameters any. I get if you don't want to pollute the myzod namespace, but it'd be great if maybe there was a Types module or something like this that had an enumeration of the types I'm publicly being returned or being forced to set as a function parameter. Thanks for the consideration!

**Comment by DavidRigglemanININ** [comment]
Another case where types would be helpful would be for catching errors and if I want to do an instanceof check on to see if it's a ValidationError. Now I can work around this by string matching the exception name, but that doesn't seem like best practice to couple myself to an internal string in the library.

**Comment by davidmdm** [comment]
@DavidRigglemanININ I believe the ValidationError class is available publicly, and so you can do:
```ts
import * as mz from 'myzod';

const result = someSchema.try(someValue);
if (result instanceof mz.ValidationError) {
  ...
}
```

As for granularity, the proposed approach is to use predicates!
So to make an integer schema I would do:

```ts
const intSchema = mz.number().withPredicate(Number.isInteger, "value must be an integer");
```

That being said I have been considering making the "Type" classes available, and I see no reason not to do so, so I will make a release soon with all the extra types available.

I am curious in understanding some use cases you have that you need to wrap with extra functionality?

Thanks for the compliments on the module.

**Comment by DavidRigglemanININ** [comment]
I was able to find the Validation class. I had missed that so thanks! Unfortunately, some others are missing that I'm currently stumped on how to solve. For example, I'm trying to create this wrapper
```
export function createSchema<T>(shape: T) {
    return myzod.object<T>(shape);
}
```
However, TS is not happy because object<T> complains that T does not satisfy the constraint ObjectShape, but I can't find any way to get access to this type to make TS happy. Ultimately, what I'm trying to do is to create an abstraction around myzod so all my schema request classes aren't using myzod directly to make it very easy to swap out in the future if I would need to. 

Also I completely understand the the desire to not have to support all possible variations of validation someone might want and think your approach is very reasonable in making predicates easy enough to use and also keeps the code base smaller, which I appreciate. One example of a type wrapper I have is to validate + map ISO-8601 strings to dayjs objects. I'm currently doing something like this
```
export function dateTimeType() {
    return myzod
        .string()
        .map(value => {
            const date = dayjs(value, ["YYYY-MM-DDTHH:mm:ss[Z]", "YYYY-MM-DDTHH:mm:ss.SSS[Z]"], true)
            return { raw: value, date }
        })
        .withPredicate(value => value.date.isValid(), value => `date time must be formatted in valid ISO-8601 format but got "${value.raw}"`)
        .map(value => value.date);
}
```
And then combined with above, what I'm trying to ultimately do is be able to define a schema like
```
export const MyQueryRequestSchema = createSchema({
    startDate: dateTimeType(),
    endDate: dateTimeType()
});

MyQueryRequestSchema.parse(json);
```

**Comment by davidmdm** [comment]
@DavidRigglemanININ 
Ok, I can help you with this! I just pushed myzod v1.8.0 that added a couple types that are just useful to have but that weren't necessarily needed (But are nice to have like `ObjectShape`) but here we go!

```ts
import * as mz from 'myzod';

function createSchema<T extends mz.ObjectShape>(shape: T) {
  return mz.object(shape);
}
```

**Comment by davidmdm** [comment]
@DavidRigglemanININ  I just pushed v1.8.1 with All base type classes exported so you can define your return types:

```ts
import * as mz from 'myzod';

function createSchema<T extends mz.ObjectShape>(shape: T): mz.ObjectType<T> {
  return mz.object(shape);
}
```

**Comment by DavidRigglemanININ** [comment]
Thanks so much for the quick response!

**Comment by DavidRigglemanININ** [comment]
So I went through and am good on all my types now except for one: MappedType. Example usage is the code snippet of the dateTimeType function I pasted above.

**Comment by davidmdm** [comment]
Just published it!

**Comment by DavidRigglemanININ** [comment]
I was able to update and complete typing all functions and make the eslint rule happy. Much thanks again and feel free to close out this issue.
