### ISSUE TITLE
Exporting z.record fails because of keySignature when using composite

### ISSUE THREAD

**Issue by johnpyp** [davidmdm/myzod#47]
We've recently run into a typescript error when exporting schemas made with z.record, given this minimal example:

`src/index.ts`
```typescript
import * as z from "myzod";

export const myTypeSchema = z.record(z.string());
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "composite": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "target": "ES6"
  },
  "include": ["src/**/*"]
}
```

This is the error:
```
src/index.ts:3:14 - error TS4023: Exported variable 'myTypeSchema' has or is using name 'keySignature' from external module "/home/johnpyp/random/myzod-bug-test/node_modules/myzod/libs/index" but cannot be named.

3 export const myTypeSchema = z.record(z.string());
               ~~~~~~~~~~~~


Found 1 error.
```

If the schema isn't exported, the error goes away.

Additionally, If `composite` is set to false, the error also goes away. `composite` is specifically used for using typescript project references so you can use individual typescript packages in a monorepo-like setting easily. The error suggests that this is part of the issue - type resolution for `keySignature` when compiling for external consumption with project references isn't possible because it isn't "named"/in scope.

https://github.com/microsoft/TypeScript/issues/5711 gives some insight on the root cause, but none of the proposed solutions here seem to work (at least in the way I interpreted them).

For now we're using a workaround that seems to work, presumably because keySignature is explicitly used/brought into scope:
```typescript
import z, { Infer } from "myzod";

export const testType = z.object({
  [z.keySignature]: z.string(),
});
```

Issue https://github.com/davidmdm/myzod/issues/42 mentions `keySignature`, and the possibility that `import * as z from 'myzod'` works when `import z from 'myzod'` doesn't, but in my testing it doesn't matter for the z.record issue at least.

**Comment by davidmdm** [comment]
Currently at a loss for as how to resolve this issue. The `keySignature` is exported so I am not sure why typescript cannot name it.
Will delve into it more when I have more time.

**Comment by magne4000** [comment]
I have the same issue with non-composite project. Just using the `record` type generates the error.
I found a workaround through:
```ts
import myzod, { AnyType } from 'myzod';

// Use this record type instead
// Works only when used in the file it's declared in
function record<T extends AnyType>(schema: T) {
  return myzod.object({
    [myzod.keySignature]: schema,
  });
}
```
