### ISSUE TITLE
Add Support to return the exact schema that is passed to Infer<T> instead of returning optional schemas

### ISSUE THREAD

**Issue by SchneiderOr** [davidmdm/myzod#55]
Hey, first of all myzod is an awesome library!!! ive moved over from zod to use this due to the impact on performance of zod
When i started type my models using myzod i noticed that the returned schema from Infer<T> always returned with all the schema fields as optional parameters even though i explicitly required them, i wonder if there is any way of marking one param or another as required for the return type

See my example 

```typescript

const userLoginParams = z.object({
  email: z.string(),
  password: z.string(),
})

const userLoginParamsAllRequired = z.required(
  z.object({
    email: z.string(),
    password: z.string(),
  }),
)

const userLoginParamsIndividualyRequired = z.object({
  email: z.required(z.string()),
  password: z.required(z.string()),
})

export type UserLoginParams = Infer<typeof userLoginParams> // type UserLoginParams = { email?: string; password?: string; }
export type UserRequiredLoginParams = Infer<typeof userLoginParamsAllRequired> // type UserLoginParams = { email?: string; password?: string; }
export type UserLoginParamsIndividualyRequired = Infer<typeof userLoginParamsIndividualyRequired> // type UserLoginParams = { email?: string; password?: string; }

```

I understand the logic behind returning optional to all the schema cause we cant be entirely sure if the validation will pass or not during runtime, but im not sure i understand why my inferred interface is optional as well

i wouldve expect al least one way or another to achieve this 
```typescript 
const userParamsSchema = z.object({
  email: z.required(z.string()),
  password: z.required(z.string()),
})

type UserLoginParams = Infer<typeof userParamsSchema> // { email: string, password: string }

```

Im able to override and add the required on the infered type, but id like to be able to control it from within the myzod api and not interrupt from typescript

```typescript 
const userParamsSchema = z.object({
  email: z.required(z.string()),
  password: z.required(z.string()),
})

// Using Required on the Inferred type, but it wont allow us to select what specific fields are required and which fields are optional, its better to derive the whole return type from the Infer<typeof schema>
type UserLoginParamsForced = Required<Infer<typeof userParamsSchema>>// { email: string, password: string }

```

im able to choose what fields are really required with the Required ts util from ts-toolbelt but its kinda duplicating the code since i already declared using myzod which fields are required
<img width="873" alt="Screenshot 2022-12-22 at 18 06 17" src="https://user-images.githubusercontent.com/17218551/209174914-2e6722f0-06c3-4262-938f-1249653081b5.png">

any help will be appreciated!

**Comment by TotalLag** [comment]
@SchneiderOr sorry to hijack and completely unrelated to your question, but how did you get vscode to expand myzod's infer? Mine always show 'any':

![image](https://user-images.githubusercontent.com/1744428/209272221-6bf6953f-2edf-4be4-8554-91872166f5b1.png)

For your actual question, have you tried LoginSchema.parse() on the data that's returned to validate? Maybe it's a VSCode UI thing, but from my experience, unless I specified  myzod.string().optional(), parse typically kicks back an error during run-time. 

Maybe not as useful, but it's the only thing I can lean on since everything is 'any' to me... 😅

**Comment by davidmdm** [comment]
I'm away for the holidays so I cannot delve too much, however I believe that this is a tsconfig issue. Try tweaking strictness. It shouldn't be optional. Generally I recommend using strict true.
